export const pets = [
  ['bear', 5],
  ['black-cat', 5],
  ['bunny', 5],
  ['chick', 3],
  ['dog', 2],
  ['frog', 3],
  ['giraffe', 4],
  ['hedgehog', 3],
  ['hippo', 5],
  ['horse', 4],
  ['koala', 4],
  ['lion', 4],
  ['monkey', 2],
  ['owl', 2],
  ['penguin', 5],
  ['pig', 2],
  ['sheep', 4],
  ['tiger', 5],
  ['turtle', 3],
  ['white-cat', 5]
]